### ISSUE TITLE
Get Data from server

### ISSUE THREAD

**Issue by Maaz77** [shiraz-uni/se-front#1]
@shiraz-uni/se-backend @shiraz-uni/se-frontend 

- How to use MyKit? define the input and output of each function!

- We must have a student type as an enum, but you parsed it as string, would you change it to enum?

**Comment by hosseindehghanipour1998** [comment]
As you can see there is only one public function in MyKit class called studentLogin.give it a username & a password and then you will have a Student object. There was a problem with Threads for requesting to the server ... so if you call the studentLogin once , it will fill all the data available in a Static Student object defined in Students class . Check both Student class and MyKit class in order to realize what i mean!
